<?php

namespace Database\Seeders;

use App\Models\Employee;
use App\Models\Department;
use App\Models\Position;
use App\Models\AssetLocation;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * Departments and positions key off 'name'; AssetLocation keys off
     * 'location_name'. Any value not already seeded is created on the fly.
     */
    public function run(): void
    {
        $employees = [
            ['employee_code' => '3030', 'name' => 'L.C. Mohammad Abdul Bari (Rtd.)', 'department' => 'Admin & HR', 'designation' => 'GM', 'father_name' => 'Mohammad Abdul Wadud', 'mother_name' => 'Shakhina Begum', 'nid_number' => '5974751777', 'present_address' => 'House # 978, Road # 15, Avenue # 2, Mirpur D O H S,Dhaka', 'permanent_address' => 'House # 978, Road # 15, Avenue # 2, Mirpur D O H S,Dhaka, Bangladesh', 'mail_address' => 'bari@norbangroup.com', 'mobile' => '01755-511833', 'join_date' => '2022-08-01', 'location' => 'NCL'],
            ['employee_code' => '1002', 'name' => 'Fazlul Karim', 'department' => 'Admin & HR', 'designation' => 'AGM', 'father_name' => 'Md. Osman Gani', 'mother_name' => 'Mst. Jahiran Begum', 'nid_number' => '2610413990237', 'present_address' => 'House # 351, Adorsho Nogor, Middle Badda, Dhaka', 'permanent_address' => 'Vill # Maidam, P. O # Fulkumar, P. S # Bhurungamari, Kurigram', 'mail_address' => 'fkarim@norbangroup.com', 'mobile' => '01755-511835', 'join_date' => '2005-02-01', 'location' => 'HAL'],
            ['employee_code' => '1013', 'name' => 'Musfique Adnan', 'department' => 'Admin & HR', 'designation' => 'Sr.Manager', 'father_name' => 'Md. Abdul Wadud', 'mother_name' => 'Mst. Masuma Jesmin', 'nid_number' => '735 188 0765', 'present_address' => 'House # 293, Road # 7 / A, Block # E, Bashundhara R /  A, Vatara, Dhaka', 'permanent_address' => 'Fazlul Haq Road, Bhoter Diar, P. O # Sirajganj Sadar - 6700, P. S # Sirajganj Sadar', 'mail_address' => 'adnan@norbangroup.com', 'mobile' => '01755-511837', 'join_date' => '2024-07-01', 'location' => 'NCL'],
            ['employee_code' => '11109', 'name' => 'Monwar Hossain', 'department' => 'Admin & HR', 'designation' => 'Manager (Comp)', 'father_name' => 'Amir Hossain', 'mother_name' => 'Setara Begum', 'nid_number' => '3281212930', 'present_address' => 'House-14, Road-23, Sector-7, Uttora, Dhaka', 'permanent_address' => 'House - 213, E - Block, N S Town, Jessore', 'mail_address' => 'monowar.compliance@norbangroup.com', 'mobile' => '01755-511834', 'join_date' => '2018-11-01', 'location' => 'NCL'],
            ['employee_code' => '1007', 'name' => 'Arifur Rahaman Khan', 'department' => 'Admin & HR', 'designation' => 'Sr.Executive', 'father_name' => 'Md. Azizur Rahaman Khan', 'mother_name' => 'Hazera Begum', 'nid_number' => '869 606 9577', 'present_address' => '235 Sultangonj Road, Rayer Bazar, Dhanmondi, Dhaka-1209', 'permanent_address' => '235 Sultangonj Road, Rayer Bazar, Dhanmondi, Dhaka-1209', 'mail_address' => 'arif.khan@norbangroup.com', 'mobile' => '01755-511839', 'join_date' => '2013-06-02', 'location' => 'NCL'],
            ['employee_code' => '1505', 'name' => 'Hossain Md.Delower (Joy)', 'department' => 'Admin & HR', 'designation' => 'Sr.Executive', 'father_name' => 'Md. Chan Mia', 'mother_name' => 'Salma Begum', 'nid_number' => '269 903 863 88', 'present_address' => '242/1, West Nakhal Para, Tejgoan, Dhaka', 'permanent_address' => '242/1, West Nakhal Para, Tejgoan, Dhaka', 'mail_address' => null, 'mobile' => '01755-511896', 'join_date' => '2007-11-01', 'location' => 'HAL'],
            ['employee_code' => '1005', 'name' => 'Abdulla-Al-Mamun (Mamun)', 'department' => 'IT', 'designation' => 'Manager', 'father_name' => 'Mohammad Ibrahim', 'mother_name' => 'Rahima Khanom', 'nid_number' => '2694259594888', 'present_address' => '91, New Polton, Azimpur, Dhaka', 'permanent_address' => '91, New Polton, Azimpur, Dhaka', 'mail_address' => 'almamun@norbangroup.com', 'mobile' => '01755-511840', 'join_date' => '2012-07-05', 'location' => 'NCL'],
            ['employee_code' => '1021', 'name' => 'Khalid Hosain FCA', 'department' => 'Accounts & Finance', 'designation' => 'CFO', 'father_name' => 'Mohammed Hussain', 'mother_name' => 'Jahanara Begum', 'nid_number' => '283 116 5325', 'present_address' => 'Hose - 4, Flat - 4 B, Road - 19, Sector - 7, Uttora Model Town T S O,', 'permanent_address' => 'Hose - 4, Flat - 4 B, Road - 19, Sector - 7, Uttora Model Town T S O,', 'mail_address' => 'khalid@norbangroup.com', 'mobile' => '01755-511843', 'join_date' => '2020-06-01', 'location' => 'NCL'],
            ['employee_code' => '2025', 'name' => 'Hafizur Rahaman', 'department' => 'Accounts & Finance', 'designation' => 'DGM', 'father_name' => 'Md. Abdul Aziz', 'mother_name' => 'Hafeza Begum', 'nid_number' => '462 162 1103', 'present_address' => 'House - 204, East Kafrul, Dhaka', 'permanent_address' => 'Vill - Khardo Khalishpur, P. O - Khalishpur, P. S - Maheshpur, Jhenaidah', 'mail_address' => 'hafizur@norbangroup.com', 'mobile' => '01755-511777', 'join_date' => '2024-10-16', 'location' => 'NCL'],
            ['employee_code' => '2026', 'name' => 'Shaikh Muzibur Rahman', 'department' => 'Accounts & Finance', 'designation' => 'AGM', 'father_name' => 'Shaikh Abdul Wohab', 'mother_name' => 'Moshammad Mahmuda Begum', 'nid_number' => '823 545 0783', 'present_address' => 'House # 532, Lane # 11, Baridhara D O H S, Dhaka # 1205', 'permanent_address' => 'Jabal E Noor Bhavan, Holding # 34/1, S. S Academy Road, Tongi College Gate, Gazipur, Dhaka', 'mail_address' => null, 'mobile' => '01912-571330', 'join_date' => '2025-08-02', 'location' => 'NCL'],
            ['employee_code' => '10029', 'name' => 'Shamim Miah', 'department' => 'Accounts & Finance', 'designation' => 'AGM', 'father_name' => 'Md. Abdul Baset Mia', 'mother_name' => 'Momotaz Begum', 'nid_number' => '9322808545595', 'present_address' => 'T B  Gate, Mohakhali, Dhaka', 'permanent_address' => 'House # 191, Road # Shantinagar, P. S # Ghatail, Tangail', 'mail_address' => 'shamim@norbangroup.com', 'mobile' => '01755-511808', 'join_date' => '2006-01-03', 'location' => 'HAL'],
            ['employee_code' => '2001', 'name' => 'Zulfiqar Hossain', 'department' => 'Accounts & Finance', 'designation' => 'Manager', 'father_name' => 'Md. Mokbul Hossain', 'mother_name' => 'Mrs. Jahanara Begum', 'nid_number' => '2611038708659', 'present_address' => 'Uttora, Dhaka', 'permanent_address' => 'House - E 17, Block - E, Word - 11, Malatinagar, Bogra - 5800', 'mail_address' => 'zulfiqar@norbangroup.com', 'mobile' => '01755-511846', 'join_date' => '2004-05-22', 'location' => 'HAL'],
            ['employee_code' => '2002', 'name' => 'Monirul Islam', 'department' => 'Accounts & Finance', 'designation' => 'Manager', 'father_name' => 'Md. Anowar Hossain', 'mother_name' => 'Moniza Khatun', 'nid_number' => '8681043447', 'present_address' => 'House # 24, Floor # 4 Th, Bashabo,Dhaka', 'permanent_address' => '7 / C, Tajmohal Road, Mohammadpur, Dhaka', 'mail_address' => 'monirul@norbangroup.com', 'mobile' => '01755-511778', 'join_date' => '2009-05-16', 'location' => 'NCL'],
            ['employee_code' => '2010', 'name' => 'Jahidur Rahman', 'department' => 'Accounts & Finance', 'designation' => 'Manager', 'father_name' => 'Md. Abdur Rashid', 'mother_name' => 'Shaleha Begum', 'nid_number' => '4126109000004', 'present_address' => 'House # 432, Plot # 3900, Bagan Bari, Shadhinata Sarani, Uttar Badda, Dhaka', 'permanent_address' => 'Vill # Bijoyrampur, P. O # Monirampur, P. S # Monirampur, Jessore', 'mail_address' => 'jahid.accounts@norbangroup.com', 'mobile' => '01755-511774', 'join_date' => '2013-09-01', 'location' => 'NCL'],
            ['employee_code' => '10038', 'name' => 'Shahin Mahmud', 'department' => 'Accounts & Finance', 'designation' => 'Manager', 'father_name' => 'Md. Roushan Ali', 'mother_name' => 'Most. Sajeda Khatun', 'nid_number' => '8816765397965', 'present_address' => 'Dhaka Uddan, Mohammadpur, Dhaka', 'permanent_address' => 'Vill # Jamirta, P. O # Jamirta. P. S # Shahajadpur,Shirajgonj', 'mail_address' => 'shahin@norbangroup.com', 'mobile' => '01755-511809', 'join_date' => '2009-06-01', 'location' => 'HAL'],
            ['employee_code' => '10041', 'name' => 'Abdullah Hil Aman', 'department' => 'Accounts & Finance', 'designation' => 'Asst.Manager', 'father_name' => 'Md. Abdul Mazid', 'mother_name' => 'Sufia Nasrin', 'nid_number' => '19854111194091', 'present_address' => 'Md. Abdul Matin, H - F # 389/1262, Pl # 444/1, Len # 2, Word # 06, Middle Azompur, Uttara, Dhaka', 'permanent_address' => 'Vill # Durgapur ( Rosulpur ), Post # Ramkrishnapur, P. S # Choughacha, Dist # Jessore', 'mail_address' => 'aman.accounts@norbangroup.com', 'mobile' => '01755-511779', 'join_date' => '2021-09-02', 'location' => 'HAL'],
            ['employee_code' => '2017', 'name' => 'Faizul Islam', 'department' => 'Accounts & Finance', 'designation' => 'Asst.Manager', 'father_name' => 'Md. Khorshed Alom', 'mother_name' => 'Lutfunnessa', 'nid_number' => '2698880376173', 'present_address' => '85 Hrishikesh Das Road, Luxmibazar,Dhaka', 'permanent_address' => '85 Hrishikesh Das Road, Luxmibazar,Dhaka', 'mail_address' => 'faizul@norbangroup.com', 'mobile' => '01755-511771', 'join_date' => '2015-12-19', 'location' => 'NCL'],
            ['employee_code' => '2024', 'name' => 'Kamal Banik', 'department' => 'Accounts & Finance', 'designation' => 'Sr.Executive', 'father_name' => 'Kartik Banik', 'mother_name' => 'Rekha Banik', 'nid_number' => '599 437 2612', 'present_address' => '49/3 R. K Mission Road, Flat # D-1, Dhaka # 1203', 'permanent_address' => '49/3 R. K Mission Road, Flat # D-1, Dhaka # 1203', 'mail_address' => 'kamal.accounts@norbangroup.com', 'mobile' => '01755-511772', 'join_date' => '2024-03-19', 'location' => 'NCL'],
            ['employee_code' => '2013', 'name' => 'Hosne Ara Begum', 'department' => 'Accounts & Finance', 'designation' => 'Sr.Executive', 'father_name' => 'Md. Anwar Hossain', 'mother_name' => 'Halima Khatun', 'nid_number' => '8928802109254', 'present_address' => '456 / 3 West Shewrapara, Mirpur, Dhaka # 1216', 'permanent_address' => '456 / 3 West Shewrapara, Mirpur, Dhaka # 1216', 'mail_address' => 'hosnaara@norbangroup.com', 'mobile' => '01716-693505', 'join_date' => '2015-01-17', 'location' => 'NCL'],
            ['employee_code' => '2020', 'name' => 'Ashik Ahmed', 'department' => 'Accounts & Finance', 'designation' => 'Sr.Executive', 'father_name' => 'Aziz Ahmed', 'mother_name' => 'Shahana Aziz', 'nid_number' => '641 365 2642', 'present_address' => '711, Monipur, P. O # Mirpur, P. S # Mirpur, Dhaka - 1216', 'permanent_address' => '711, Monipur, P. O # Mirpur, P. S # Mirpur, Dhaka - 1216', 'mail_address' => 'ashik.accounts@norbangroup.com', 'mobile' => '01755-511775', 'join_date' => '2021-08-07', 'location' => 'NCL'],
            ['employee_code' => '2004', 'name' => 'Masud Ahmed', 'department' => 'Audit', 'designation' => 'Sr.Manager', 'father_name' => 'Abdul Gopran', 'mother_name' => 'Delara Begum', 'nid_number' => '7518038862278', 'present_address' => 'Rampura, Banasree, Dhaka', 'permanent_address' => 'Vill # Nolua, P. O # Kankirhat, P. S # Senbagh, Noakhali', 'mail_address' => 'masud.audit@norbangroup.com', 'mobile' => '01755-511845', 'join_date' => '2013-04-07', 'location' => 'NCL'],
            ['employee_code' => '7032', 'name' => 'Anwarul Alam Monzu', 'department' => 'Commercial', 'designation' => 'DGM', 'father_name' => 'Md. Abdul Kader', 'mother_name' => 'Anwara Begum', 'nid_number' => '8657631837', 'present_address' => 'House # 783, Flat # 4 / B, Road # Dewan Para Model School,P. O # Azampur - 1230, Dakhin Khan, Dhaka', 'permanent_address' => 'Abdul Gani Master Bari, Shatgharia, Sharikait, Shiberhat, Sandwip, Chattogram - 4301', 'mail_address' => 'monzu@norbangroup.com', 'mobile' => '01755-511870', 'join_date' => '2024-08-20', 'location' => 'NCL'],
            ['employee_code' => '10010', 'name' => 'Shahin Sarwar', 'department' => 'Commercial', 'designation' => 'AGM', 'father_name' => 'Sayed Shahed Ali', 'mother_name' => 'Salma Begum', 'nid_number' => '2695046940411', 'present_address' => 'Sia Masjid, Mohammadpur, Dhaka', 'permanent_address' => 'Vill # Balubari Shahid Minar, P. O # Balubari, P. S #  Dinajpur Sadar, Dinajpur', 'mail_address' => 'sarwar@norbangroup.com', 'mobile' => '01755-511814', 'join_date' => '2006-02-12', 'location' => 'HAL'],
            ['employee_code' => '7029', 'name' => 'Atiqur Rahman Khan', 'department' => 'Commercial', 'designation' => 'AGM', 'father_name' => 'Nurul Islam Khan', 'mother_name' => 'Khaleda Begum', 'nid_number' => '5524942470', 'present_address' => '151/16, Mukti Koloni, South Pirerbag, Mirpur, Dhaka', 'permanent_address' => '38, B- C, R- Green Road, Tangail - 1900', 'mail_address' => 'atiq@norbangroup.com', 'mobile' => '01755-511873', 'join_date' => '2022-09-26', 'location' => 'NCL'],
            ['employee_code' => '7006', 'name' => 'Parvez', 'department' => 'Commercial', 'designation' => 'Manager', 'father_name' => 'Md. Hanif', 'mother_name' => 'Nasim Akhter', 'nid_number' => '0911814137052', 'present_address' => 'Plot # 3900 Bagan Bari, Balur Math, Shadinata Sarani, North Badda, Dhaka', 'permanent_address' => 'Weather Office Road, Bhola Sadar, Bhola', 'mail_address' => 'parvez@norbangroup.com', 'mobile' => '01755-511714', 'join_date' => '2014-10-10', 'location' => 'NCL'],
            ['employee_code' => '10099', 'name' => 'Abdul Ahad Molla', 'department' => 'Commercial', 'designation' => 'Manager', 'father_name' => 'Abdus Samad Molla', 'mother_name' => 'Rawson Ara Begum', 'nid_number' => '6726814568821', 'present_address' => 'Vill # Rupshi, P. O # Rupshi Bazar, P. S # Rupganj.Dist # Narayanganj', 'permanent_address' => 'Vill # Rupshi, P. O # Rupshi Bazar, P. S # Rupganj.Dist # Narayanganj', 'mail_address' => 'ahad@norbangroup.com', 'mobile' => '01755-511875', 'join_date' => '2022-11-07', 'location' => 'HAL'],
            ['employee_code' => '7001', 'name' => 'S.M Masuduzzaman', 'department' => 'Commercial', 'designation' => 'Deputy Manager', 'father_name' => 'Md. Ishaque Sharif', 'mother_name' => 'Mrs. Rashida Haque', 'nid_number' => '2694803580040', 'present_address' => '127/4 (4 Th Floor) Ulon, West Rampura, Dhaka', 'permanent_address' => 'Nahar Manjil, 4/5 C , Rupatoli Housing State, Barishal', 'mail_address' => 'masud@norbangroup.com', 'mobile' => '01755-511711', 'join_date' => '2010-12-01', 'location' => 'NCL'],
            ['employee_code' => '10239', 'name' => 'Shafiqul Kabir', 'department' => 'Commercial', 'designation' => 'Asst.Manager', 'father_name' => 'Md.Kabir Uddin Molla', 'mother_name' => 'Rashida Begum', 'nid_number' => '7618319318581', 'present_address' => 'Badda, Dhaka', 'permanent_address' => 'Vill - Chardulai, P . O - Dulai, P . S - Sujanagar,', 'mail_address' => 'kabir@norbangroup.com', 'mobile' => '01755-511816', 'join_date' => '2010-08-10', 'location' => 'HAL'],
            ['employee_code' => '7023', 'name' => 'Sultan Mahmud Khan', 'department' => 'Commercial', 'designation' => 'Asst.Manager', 'father_name' => 'Abdul Gani Khan', 'mother_name' => 'Sufia Bagum', 'nid_number' => '4183021189', 'present_address' => '331 / C Habir Tek, Kunchkora, Uttar Khan, Dhaka', 'permanent_address' => '331 / C Habir Tek, Kunchkora, Uttar Khan, Dhaka', 'mail_address' => 'sultankhan@norbangroup.com', 'mobile' => '01755-511716', 'join_date' => '2022-09-01', 'location' => 'NCL'],
            ['employee_code' => '7004', 'name' => 'Dayal Das', 'department' => 'Commercial', 'designation' => 'Sr.Executive', 'father_name' => 'Rampada Das', 'mother_name' => 'Momota Das', 'nid_number' => '2617680831859', 'present_address' => '362 Sontek School Road, Donia, Jatarabari, Dhaka', 'permanent_address' => '362 Sontek School Road, Donia, Jatarabari, Dhaka', 'mail_address' => 'dayal@norbangroup.com', 'mobile' => '01755-511713', 'join_date' => '2012-06-12', 'location' => 'NCL'],
            ['employee_code' => '7024', 'name' => 'Ibrahim Mizi', 'department' => 'Commercial', 'designation' => 'Sr.Executive', 'father_name' => 'Md. Dudu Mia', 'mother_name' => 'Lily Begum', 'nid_number' => '4162119434', 'present_address' => 'Ka - 175/2, Flat # 06, Floor # 4 Th, Kuril Kazi Bari, Batara', 'permanent_address' => 'Vill # Chhota Sundar, P. O # Algi Panch Goan, P. S # Chandpur', 'mail_address' => 'ibrahim@norbangroup.com', 'mobile' => '01755-511815', 'join_date' => '2022-09-06', 'location' => 'NCL'],
            ['employee_code' => '7025', 'name' => 'Biplob Hossen', 'department' => 'Commercial', 'designation' => 'Sr.Executive', 'father_name' => 'Md. Abdul Hamid', 'mother_name' => 'Mrs. Marioum Khatun', 'nid_number' => '5063301971', 'present_address' => 'House # 468, Road # 31, New D O H S, Mohakhali, Dhaka # 1206', 'permanent_address' => 'Vill # Gadhuli, Sathia, Sathia, Pabna 6670', 'mail_address' => 'biplob@norbangroup.com', 'mobile' => '01755-511872', 'join_date' => '2022-09-10', 'location' => 'NCL'],
            ['employee_code' => '7026', 'name' => 'Salauddin', 'department' => 'Commercial', 'designation' => 'Sr.Executive', 'father_name' => 'Sirajul Hoque', 'mother_name' => 'Amina Begum', 'nid_number' => '4635210562', 'present_address' => 'Bowmoni Beauty Parllour Building (6th Floor), 58/2 Boishaki Sarani, Middle Badda, Gulshan # 01, Dhaka # 1212', 'permanent_address' => 'Vill # Aochia (muktar Bari), P. O # Deodigi (4386), P. S # Satkania, Dist # Chattogram', 'mail_address' => 'salauddin@norbangroup.com', 'mobile' => '01755-511877', 'join_date' => '2022-10-22', 'location' => 'NCL'],
            ['employee_code' => '10240', 'name' => 'Tareq Ahmed Oli', 'department' => 'Commercial', 'designation' => 'Executive', 'father_name' => 'Mr. Aziz Ahmed', 'mother_name' => 'Mr. Aziz Ahmed', 'nid_number' => '2380690814', 'present_address' => '711, Monipur, Mirpur-2, Dhaka-1216', 'permanent_address' => '711, Monipur, Mirpur-2, Dhaka-1216', 'mail_address' => 'tariq@norbangroup.com', 'mobile' => '01755-511787', 'join_date' => '2019-07-01', 'location' => 'HAL'],
            ['employee_code' => '7022', 'name' => 'Bijon Biswas', 'department' => 'Commercial', 'designation' => 'Executive', 'father_name' => 'Girindra Nath Biswas', 'mother_name' => 'Gita Rani Biswas', 'nid_number' => '8210717733005', 'present_address' => 'House # 378/1a (4th Floor D-3), Iqbal Road, West Shawrapara, Mirpur, Dhaka- 1216,', 'permanent_address' => 'Vill # Baharpur, P. O # Baharpur, P. S # Baliakandi, Dist # Rajbari', 'mail_address' => 'bijon@norbangroup.com', 'mobile' => '01755-511712', 'join_date' => '2022-01-04', 'location' => 'NCL'],
            ['employee_code' => '7027', 'name' => 'Biswajit Biswas', 'department' => 'Commercial', 'designation' => 'Executive', 'father_name' => 'Khokon Chandra Biswas', 'mother_name' => 'Kironi Bala', 'nid_number' => '3744886692', 'present_address' => 'Bilquis Tower (9th Floor), Gulshan - 2,', 'permanent_address' => 'Vill # Tarashi, P. O # Madhyapolli, P. S # Narail Sadar', 'mail_address' => 'bishwajit@norbangroup.com', 'mobile' => '01755-511882', 'join_date' => '2022-10-30', 'location' => 'NCL'],
            ['employee_code' => '7016', 'name' => 'Jubayer Khan', 'department' => 'Commercial', 'designation' => 'Jr.Executive', 'father_name' => 'Md. Nasir Uddin Khan', 'mother_name' => 'Maksuda Begume', 'nid_number' => '734 687 9104', 'present_address' => 'Dhaka', 'permanent_address' => 'Vill # Rajpasha, Post # Shakerhat, Upozila # Jhalakathi', 'mail_address' => 'jubayer@norbangroup.com', 'mobile' => '01755-511818', 'join_date' => '2020-11-10', 'location' => 'NCL'],
            ['employee_code' => '10098', 'name' => 'Fahmida Islam', 'department' => 'Commercial', 'designation' => 'Jr.Executive', 'father_name' => 'Mofizul Islam', 'mother_name' => 'Mahmuda Islam', 'nid_number' => '8244829050', 'present_address' => 'House # 10, Road # 02, Block # L, Banani', 'permanent_address' => 'House # 10, Road # 02, Block # L, Banani', 'mail_address' => 'fahmida@norbangroup.com', 'mobile' => '01755-511881', 'join_date' => '2021-10-02', 'location' => 'HAL'],
            ['employee_code' => '7033', 'name' => 'Muhammad Sayed Ali', 'department' => 'Commercial', 'designation' => 'Sr.Executive (Custom Sarker)', 'father_name' => 'Abdul Majid Munsi', 'mother_name' => 'Sakhina Begum', 'nid_number' => '866 080 2763', 'present_address' => 'Hose # 176, Ashkona, P. O # Haji Camp - 1230, P. S # Dakshinkhan, Dhaka', 'permanent_address' => 'Vill # Patadaha, P. O # Patadaha - 2012, P. S # Madarganj, Jamalpur', 'mail_address' => null, 'mobile' => '01979-333581', 'join_date' => '2026-01-01', 'location' => 'NCL'],
            ['employee_code' => '7021', 'name' => 'Shampa Biswas', 'department' => 'Commercial', 'designation' => 'Jr.Executive', 'father_name' => 'Swapan Kumar Biswas', 'mother_name' => 'Purnima Biswas', 'nid_number' => '2695435086727', 'present_address' => '192/1, Shantibag, Dhaka - 1217', 'permanent_address' => 'Vill # Banigram, P. O # Bashkhali, P. S # Bashkhali, Chittagong', 'mail_address' => 'shampa@norbangroup.com', 'mobile' => '01755-511710', 'join_date' => '2021-11-01', 'location' => 'NCL'],
            ['employee_code' => '10096', 'name' => 'Nazimuddin', 'department' => 'Commercial', 'designation' => 'Jr.Executive', 'father_name' => 'Abdul Hamid', 'mother_name' => 'Mst. Orabullah Begum', 'nid_number' => '4817966931406', 'present_address' => 'Middle Badda, Dhaka', 'permanent_address' => 'Vill - Porabaria, P . O. #  Purbo Narandi, P. S # Pakondi, Kishorgonj', 'mail_address' => null, 'mobile' => '01755-511817', 'join_date' => '2006-03-25', 'location' => 'HAL'],
            ['employee_code' => '7031', 'name' => 'Souleman', 'department' => 'Commercial', 'designation' => 'Massanger', 'father_name' => 'Md. Matin', 'mother_name' => 'Amena Khatun', 'nid_number' => '2693622412729', 'present_address' => 'Vill # Mazukhan, P. O # Ratanpur, P. S # Kaliakoir, Gazipur', 'permanent_address' => 'Vill # Mojit Matbargram, P. O # Dhewkhali, P. S # Sadarbari, Faridpur', 'mail_address' => null, 'mobile' => '01723-454440', 'join_date' => '2023-08-01', 'location' => 'NCL'],
            ['employee_code' => '3009', 'name' => 'Kahairul Islam', 'department' => 'Procurement', 'designation' => 'AGM', 'father_name' => 'Zahurul Haque', 'mother_name' => 'Mrs. Anowara Haque', 'nid_number' => '2695047980471', 'present_address' => 'Babor Road, Mohammadpur', 'permanent_address' => 'House # 172, Road # 1/10, Block # 2/5, Dayamoyapara, Jamalpur', 'mail_address' => 'khairul.pr@norbangroup.com', 'mobile' => '01755-511684', 'join_date' => '2012-09-02', 'location' => 'NCL'],
            ['employee_code' => '3004', 'name' => 'Anisul Alam', 'department' => 'Procurement', 'designation' => 'AGM', 'father_name' => 'Md. Zahurul Haque', 'mother_name' => 'Mrs. Anowara Haque', 'nid_number' => '3923605136862', 'present_address' => 'Babar Road, Mohqmmadpu', 'permanent_address' => 'House # 172, Road # 1/10, Block # 2/5, Dayamoyapara, Jamalpur', 'mail_address' => 'mithu@norbangroup.com', 'mobile' => '01755-511853', 'join_date' => '2006-04-01', 'location' => 'NCL'],
            ['employee_code' => '3051', 'name' => 'Manjareen Siddiqua', 'department' => 'Procurement', 'designation' => 'Manager', 'father_name' => 'Monzurul Haque Siddiqui', 'mother_name' => 'Mrs.Kamrun Nahar', 'nid_number' => null, 'present_address' => 'House # 773, Block # G, Bashundhara, Dhaka', 'permanent_address' => 'House # 773, Block # G, Bashundhara, Dhaka', 'mail_address' => 'manjarin@norbangroup.com', 'mobile' => '01755-511836', 'join_date' => '2016-03-08', 'location' => 'NCL'],
            ['employee_code' => '3053', 'name' => 'Foyzur Rahman', 'department' => 'Procurement', 'designation' => 'Asst.Manager', 'father_name' => 'Md. Mafizur Rahaman', 'mother_name' => 'Ferdousi Begum', 'nid_number' => '19842691648049', 'present_address' => 'House- Pa-145-4th Floor, South Badda, Dhaka', 'permanent_address' => 'House-85, Vill- Satpai, Post- Netrokona Sadar, P. S - Netrokona', 'mail_address' => 'didar@norbangroup.com', 'mobile' => '01755-511683', 'join_date' => '2019-08-01', 'location' => 'NCL'],
            ['employee_code' => '3010', 'name' => 'Ziauddin Khan', 'department' => 'Procurement', 'designation' => 'Asst.Manager', 'father_name' => 'Md. Jalal Uddin Khan', 'mother_name' => 'Selina Akther', 'nid_number' => '4815471000134', 'present_address' => 'Badda, Dhaka', 'permanent_address' => 'Vill # Purbaghatar Chor, P.O # Bir Kashem Nagor, P.S # Kuliar Char', 'mail_address' => 'ziauddin@norbangroup.com', 'mobile' => '01709-632650', 'join_date' => '2015-03-16', 'location' => 'NCL'],
            ['employee_code' => '3016', 'name' => 'Rafiqul Islam', 'department' => 'Procurement', 'designation' => 'Asst.Manager', 'father_name' => 'Md.bahar Uddin', 'mother_name' => 'Mst. Rokeya khanam', 'nid_number' => '4916194163791', 'present_address' => 'Badda, Dhaka', 'permanent_address' => 'Vill # Nilur Khamar, Post #  Beparihat, P. S #  Nageshwari,Kurigram', 'mail_address' => 'rafiqul.pr@norbangroup.com', 'mobile' => '01709-632651', 'join_date' => '2015-04-05', 'location' => 'NCL'],
            ['employee_code' => '3019', 'name' => 'Md. Saidul Haque Mazumdar', 'department' => 'Procurement', 'designation' => 'Asst.Manager', 'father_name' => 'Abdur Rashid Mazumdar', 'mother_name' => 'Mafia Khatun', 'nid_number' => '282 628 8785', 'present_address' => 'North Shahjahanpur, Dhaka', 'permanent_address' => 'House # 90 / Kha, Vill # Masjid Bari, P. S # Nurpur, P. O # Cumilla - 3500', 'mail_address' => null, 'mobile' => '01345-912204', 'join_date' => '2026-02-23', 'location' => 'NCL'],
            ['employee_code' => '10031', 'name' => 'Ariful Islam', 'department' => 'Procurement', 'designation' => 'Sr.Executive', 'father_name' => 'Md. Moher Uddin', 'mother_name' => 'Anowara', 'nid_number' => '2713056000094', 'present_address' => 'Badda, Dhaka', 'permanent_address' => 'Vill # Dakhin Nogar, P. O # Binnakuri - 5240, Upazila: Chirirbandar, Dinajpur', 'mail_address' => 'arif.pr@norbangroup.com', 'mobile' => '01755-511819', 'join_date' => '2019-04-01', 'location' => 'HAL'],
            ['employee_code' => '3056', 'name' => 'Abdullah Al Masum', 'department' => 'Procurement', 'designation' => 'Executive', 'father_name' => 'Md. Abdul Barek', 'mother_name' => 'Safia Khatun', 'nid_number' => '19916111652000', 'present_address' => 'Badda, Dhaka', 'permanent_address' => 'Vill # Purba Baligaon, Post # Ghosgaon, P. S #  Dhobauna, Mymansing', 'mail_address' => 'masum.pr@norbangroup.com', 'mobile' => '01709-632652', 'join_date' => '2020-11-07', 'location' => 'NCL'],
            ['employee_code' => '3057', 'name' => 'Morshedul Hasan', 'department' => 'Procurement', 'designation' => 'Jr.Executive', 'father_name' => 'Mir Hafizur Rahman', 'mother_name' => 'Farida Yeasmin', 'nid_number' => '5990479411', 'present_address' => 'Zafrabad, Mohammadpur', 'permanent_address' => 'Vill # Mukundo Bari Bazrapur, P. O # Jamalpur, P. S # Jamalpur,Jamalpur', 'mail_address' => 'morshedul@norbangroup.com', 'mobile' => '01755-511838', 'join_date' => '2022-05-14', 'location' => 'NCL'],
            ['employee_code' => '3018', 'name' => 'Golam Morshad Khan', 'department' => 'Procurement', 'designation' => 'Jr.Executive', 'father_name' => 'Munsur Ahammad Khan', 'mother_name' => 'Israt Jahan Polly', 'nid_number' => '735 550 8115', 'present_address' => null, 'permanent_address' => null, 'mail_address' => null, 'mobile' => null, 'join_date' => null, 'location' => null],
            ['employee_code' => '3028', 'name' => 'Nur Mohammad', 'department' => 'Procurement', 'designation' => 'Purchase Assistant', 'father_name' => 'Nafiz Uddin', 'mother_name' => 'Most. Laily Beoan', 'nid_number' => null, 'present_address' => 'Badda, Dhaka', 'permanent_address' => 'Vill # Sarjan Kuri, P. O # Unahat Singra, P. S # Dupchachia, Dist # Bogra', 'mail_address' => null, 'mobile' => '01774-651350', 'join_date' => '2015-08-03', 'location' => 'NCL'],
            ['employee_code' => '10181', 'name' => 'Firoz', 'department' => 'Procurement', 'designation' => 'Office Assistant', 'father_name' => 'Md. Amzad Hossain', 'mother_name' => 'Mst. Farida Begum', 'nid_number' => '7623902505031', 'present_address' => 'Badda, Dhaka', 'permanent_address' => 'Vill # School Para, P. O # Ishwardi, P. S # Ishwardi, Pabna', 'mail_address' => null, 'mobile' => '01718-095272', 'join_date' => '1999-01-27', 'location' => 'HAL'],
            ['employee_code' => '3002', 'name' => 'Nashida Sharmin Zaman', 'department' => 'Merchandising', 'designation' => 'GM', 'father_name' => 'Md. Muraduzzaman', 'mother_name' => 'Nasima Zaman', 'nid_number' => '2696653260546', 'present_address' => 'Rangs Garden, Place, 63/ B, Shiddes Shari Road,Dhaka', 'permanent_address' => 'Rangs Garden Place, 63/ B, Shiddes Shari Road,Dhaka', 'mail_address' => 'rinku@norbangroup.com', 'mobile' => '01755-511851', 'join_date' => '2005-05-05', 'location' => 'NCL'],
            ['employee_code' => '3005', 'name' => 'Tanjim Mahmood', 'department' => 'Merchandising', 'designation' => 'AGM', 'father_name' => 'Mahmood Sazzad', 'mother_name' => 'Momtaz Begum', 'nid_number' => '2619551160338', 'present_address' => 'House-68, Road-1, Sector-12, Uttara, Dhaka', 'permanent_address' => 'House-68, Road-1, Sector-12, Uttara, Dhaka', 'mail_address' => 'tanjim@norbangroup.com', 'mobile' => '01755-511855', 'join_date' => '2006-11-01', 'location' => 'NCL'],
            ['employee_code' => '3006', 'name' => 'Jamiul Islam', 'department' => 'Merchandising', 'designation' => 'AGM', 'father_name' => 'Md. Abdus Samad Sarker', 'mother_name' => 'Mrs. Jaheda Begum', 'nid_number' => '2698874445419', 'present_address' => '18/1, Bonograme Lane, Warri,Dhaka-1203', 'permanent_address' => 'Matri Villa, Mogorkhal, National University, Joydebpur, Gazipur', 'mail_address' => 'jamiul@norbangroup.com', 'mobile' => '01755-511856', 'join_date' => '2006-12-02', 'location' => 'HAL'],
            ['employee_code' => '5104', 'name' => 'Md. Mahamudul Hassan Mredul', 'department' => 'Merchandising', 'designation' => 'AGM', 'father_name' => 'Md. Abdul Jabber', 'mother_name' => 'Mrs. Momena Khatun', 'nid_number' => '599 164 4815', 'present_address' => 'House # 124, Road # 07, Block # B, Section # 12, Mirpur, Pallabi,Dhaka # 1216', 'permanent_address' => 'House # 160, South Chandpur, Ward # 02, Darshana - 7221, Damurhuda, Chuadanga', 'mail_address' => null, 'mobile' => '01798-112491', 'join_date' => '2025-12-10', 'location' => 'NCL'],
            ['employee_code' => '5083', 'name' => 'Nur-Alam', 'department' => 'Merchandising', 'designation' => 'Manager', 'father_name' => 'Md. Shah Jahan', 'mother_name' => 'Saleha Begum', 'nid_number' => null, 'present_address' => '32/25 Sultangong Road, Rayer Bazar, Dhanmondi,Dhaka', 'permanent_address' => 'Vill # South Mondia, P. O # Pir Sultan, P. S # Chagolnaiya,Feni', 'mail_address' => 'nuralam@norbangroup.com', 'mobile' => '01755-511860', 'join_date' => '2020-08-05', 'location' => 'NCL'],
            ['employee_code' => '3012', 'name' => 'Hossain', 'department' => 'Merchandising', 'designation' => 'Deputy Manager', 'father_name' => 'Md. Moshab Uddin', 'mother_name' => 'Mrs. Monwara Begum', 'nid_number' => '8198507228505', 'present_address' => '51 Arcadia Dream, Purana Polton Lane,', 'permanent_address' => 'House 50, Chandipur, Raj Para Thana,Rajshahi', 'mail_address' => 'hossain@norbangroup.com', 'mobile' => '01755-511864', 'join_date' => '2011-10-01', 'location' => 'NCL'],
            ['employee_code' => '3013', 'name' => 'Shudarshan Kumar Biman', 'department' => 'Merchandising', 'designation' => 'Deputy Manager', 'father_name' => 'Mahanta Kumar sarkar', 'mother_name' => 'Anita Rani Sarkar', 'nid_number' => '2691650168081', 'present_address' => 'Zigatola, Dhanmondi, Dhaka', 'permanent_address' => 'Vill # Kushumbi, P. O # Binshara, P. S # Tarash, Sirajgong', 'mail_address' => 'biman@norbangroup.com', 'mobile' => '01755-511866', 'join_date' => '2012-05-07', 'location' => 'HAL'],
            ['employee_code' => '3001', 'name' => 'Delower Hossain', 'department' => 'Merchandising', 'designation' => 'Asst.Manager', 'father_name' => 'Abdur Rashid', 'mother_name' => 'Mrs. Anwara Begum', 'nid_number' => '8816765398302', 'present_address' => 'Basila, Dhaka', 'permanent_address' => 'Vill # Jamirta, P. O # Jamirta, P. S # Shahjadpur, Shirajgonj', 'mail_address' => 'delower@norbangroup.com', 'mobile' => '01755-511854', 'join_date' => '2005-02-01', 'location' => 'HAL'],
            ['employee_code' => '5105', 'name' => 'Khan Moh. Rezwan', 'department' => 'Merchandising', 'designation' => 'Asst.Manager', 'father_name' => 'Abdul Mannan Khan', 'mother_name' => 'Roksana Khatun', 'nid_number' => '690 097 7981', 'present_address' => 'House # 27, Road # 11, Block # M, South Banasree,Dhaka', 'permanent_address' => 'House # Khan Bari, Vill # Jogippul, P. O # Shiromoni - 9204,P. S # Digholia.Khulna', 'mail_address' => null, 'mobile' => '01762-088882', 'join_date' => '2026-04-01', 'location' => 'NCL'],
            ['employee_code' => '5102', 'name' => 'Md. Ali Asgar Rana', 'department' => 'Merchandising', 'designation' => 'Asst.Manager', 'father_name' => 'Md. Bellal Hossain', 'mother_name' => 'Fahima Akter', 'nid_number' => '643 536 2782', 'present_address' => '118/3, Dakkhin Kafrul, P. O # Cantonment - 1206, P. S # Kafrul,Dhaka', 'permanent_address' => 'Vill # Kedarpur, P. O # Marfutganj, P. S # Naria,Shariatpur', 'mail_address' => null, 'mobile' => '01620-222585', 'join_date' => '2025-11-23', 'location' => 'NCL'],
            ['employee_code' => '5103', 'name' => 'Sufi Ahmed Fahim', 'department' => 'Merchandising', 'designation' => 'Asst.Manager', 'father_name' => 'Md. Abul Basar', 'mother_name' => 'Razia Begum', 'nid_number' => '1992 131 768 2000', 'present_address' => 'House # 15, Road # 7 / A, Block # H, Banasree,Dhaka', 'permanent_address' => 'House # Nandi Bepari Bari, Vill # Ashinpur, P. S # Matlab ( South),P. O # Ashinpur - 3640,Chandpur', 'mail_address' => null, 'mobile' => '01682-793734', 'join_date' => '2025-12-01', 'location' => 'NCL'],
            ['employee_code' => '5067', 'name' => 'Sayed Junaied Kabir', 'department' => 'Merchandising', 'designation' => 'Sr.Merchandiser', 'father_name' => 'A.M. Uoynus Choudhuri', 'mother_name' => 'Sayeda Amina Begum', 'nid_number' => '2693717452635', 'present_address' => 'Uttora, Dhaka', 'permanent_address' => 'Vill # Barodaona, P. O # Barodaona, P. S # Satkania, Dist # Chittagong', 'mail_address' => 'junaid@norbangroup.com', 'mobile' => '01755-511858', 'join_date' => '2017-01-12', 'location' => 'NCL'],
            ['employee_code' => '5022', 'name' => 'Marof Amin Rupok', 'department' => 'Merchandising', 'designation' => 'Sr.Merchandiser', 'father_name' => 'Md. Golam Nabi', 'mother_name' => 'Mrs. Afruza Begum', 'nid_number' => '3923606141651', 'present_address' => 'Apartment # 2, Road # 09, Gulshan - 01', 'permanent_address' => 'House # 923, Road # 30, Block # 2/6, Mukondobari, Jamalpur', 'mail_address' => 'rupok@norbangroup.com', 'mobile' => '01709-632660', 'join_date' => '2012-09-02', 'location' => 'NCL'],
            ['employee_code' => '5047', 'name' => 'Jakia Rahman', 'department' => 'Merchandising', 'designation' => 'Sr.Merchandiser', 'father_name' => 'SK. Md. Jalilur Rahaman', 'mother_name' => 'Mukta Rahman', 'nid_number' => '2695044894715', 'present_address' => 'Badda, Dhaka', 'permanent_address' => '30/9, Block -d, Shershahshuri Road,mohammadpur,Dhaka', 'mail_address' => 'jakia@norbangroup.com', 'mobile' => '01709-632665', 'join_date' => '2015-07-07', 'location' => 'NCL'],
            ['employee_code' => '5095', 'name' => 'Sobuj Khan', 'department' => 'Merchandising', 'designation' => 'Sr.Merchandiser', 'father_name' => 'Hakim Khan', 'mother_name' => 'Hasina Begum', 'nid_number' => '822 981 0885', 'present_address' => 'Road # 05, House # 26, Block # C, Mirpur - Section # 06, Dhaka', 'permanent_address' => 'House # Pashchim Para, Vill # Daulatpur,  P. O # Daulatpur - 6740,Belkuchi, Sirajganj', 'mail_address' => 'sobuj.khan@norbangroup.com', 'mobile' => '01755-511869', 'join_date' => '2024-10-13', 'location' => 'NCL'],
            ['employee_code' => '5096', 'name' => 'Shafiqul Islam', 'department' => 'Merchandising', 'designation' => 'Sr.Merchandiser', 'father_name' => 'A. K. M. Siddiqul Islam', 'mother_name' => 'Shaila Islam', 'nid_number' => '1955156375', 'present_address' => 'House # 326-347, Road # 15, Block # A, Bashundhora R / A,Dhaka', 'permanent_address' => 'House # 1331, Vill # Miapara, Bakultola, P. O # Jamalpur,', 'mail_address' => 'shafiqul@norbangroup.com', 'mobile' => '01755-511862', 'join_date' => '2025-04-06', 'location' => 'NCL'],
            ['employee_code' => '5098', 'name' => 'Riaz Uddin', 'department' => 'Merchandising', 'designation' => 'Sr.Merchandiser', 'father_name' => 'Mohiuddin', 'mother_name' => 'Rashida Begum', 'nid_number' => '19900912585000', 'present_address' => 'Plot # 5, Road # 2, Section # 7, Mirpur,Dhaka', 'permanent_address' => 'Vill # Chartofazzal, P. O # Chartofazzal, P. S # Charfassion,Bhola', 'mail_address' => 'riaz.uddin@norbangroup.com', 'mobile' => '01755-511867', 'join_date' => '2025-06-17', 'location' => 'NCL'],
            ['employee_code' => '5101', 'name' => 'Sadi Mohammed Sami', 'department' => 'Merchandising', 'designation' => 'Sr.Merchandiser', 'father_name' => 'Din Mohammed', 'mother_name' => 'Shahina Akhter', 'nid_number' => '870 235 8600', 'present_address' => '52 / 3 / C Janata Tower, Balughat, Cantonment,Dhaka', 'permanent_address' => 'House # 44 / 1 (10 - B 1), New Market City Complex, P. O # New Market - 1205,P. S # New Market, Dhaka', 'mail_address' => null, 'mobile' => '01521-470540', 'join_date' => '2025-10-05', 'location' => 'NCL'],
            ['employee_code' => '55134', 'name' => 'Shahadat Hossain', 'department' => 'Merchandising', 'designation' => 'Merchandiser', 'father_name' => 'Md. Abdul Halim', 'mother_name' => 'Mst. Tahera Begum', 'nid_number' => '19927518315000', 'present_address' => 'House # 57, Road # 01, Block # A, Afaz Nagar Police Line, Fatullah,Dhaka', 'permanent_address' => 'Vill # Rajarampur, P. O # Amishapara. P. S # Sonaimuri,Noakhali', 'mail_address' => 'shahadat@norbangroup.com', 'mobile' => '01755-511703', 'join_date' => '2022-09-01', 'location' => 'NCL'],
            ['employee_code' => '5100', 'name' => 'Md. Sohanur Rahman Sohel', 'department' => 'Merchandising', 'designation' => 'Merchandiser', 'father_name' => 'Md. Ibrahim', 'mother_name' => 'Mst. Halima Khatun', 'nid_number' => '600 498 0303', 'present_address' => 'House # 748, Ibrahimpur, Kafrul,Dhaka', 'permanent_address' => 'House # 779, Vill # Ibrahimpur. P. O # Dhaka Cantonment - 1206,P. S # Kafrul, Dhaka', 'mail_address' => null, 'mobile' => '01623-923771', 'join_date' => '2025-10-01', 'location' => 'NCL'],
            ['employee_code' => '5106', 'name' => 'Masum Shahariar Sozib', 'department' => 'Merchandising', 'designation' => 'Merchandiser', 'father_name' => 'Shafiqul Islam', 'mother_name' => 'Jhinuk Akter', 'nid_number' => '510 465 4487', 'present_address' => 'T I C Koloni, Sector # 08, Uttara,Dhaka', 'permanent_address' => 'Vill # Vati Jagat Char, P. O # Lakhipur - 2338, P. S # Kuliar Char,Kishoregonj', 'mail_address' => null, 'mobile' => '01521-312132', 'join_date' => '2026-04-01', 'location' => 'NCL'],
            ['employee_code' => '5084', 'name' => 'Shomrat Jahangir', 'department' => 'Merchandising', 'designation' => 'Asst.Merchandiser', 'father_name' => 'Abdul Malek', 'mother_name' => 'Afia Begum', 'nid_number' => '507 714 8186', 'present_address' => '102, West Nakhal Para, Tejgaon, Dhaka- 1215', 'permanent_address' => '102, West Nakhal Para, Tejgaon, Dhaka- 1215', 'mail_address' => 'shomrat@norbangroup.com', 'mobile' => '01755-511861', 'join_date' => '2021-10-10', 'location' => 'NCL'],
            ['employee_code' => '5097', 'name' => 'Allmond Pavel', 'department' => 'Design', 'designation' => 'Manager', 'father_name' => 'Mohammad Shahabuddin', 'mother_name' => 'Nargis Akter', 'nid_number' => '9569922652', 'present_address' => '72 Monu Mia Road, P. O # Sarulia, P. S # Demra,Dhaka', 'permanent_address' => '72 Monu Mia Road, P. O # Sarulia, P. S # Demra,Dhaka', 'mail_address' => 'pavel@norbangroup.com', 'mobile' => '01755-511868', 'join_date' => '2025-04-08', 'location' => 'NCL'],
            ['employee_code' => '5099', 'name' => 'Mehedi Hasan', 'department' => 'Design', 'designation' => 'Assistant Designer', 'father_name' => 'Harun Or Rashid', 'mother_name' => 'Morium Begum', 'nid_number' => '510 093 5492', 'present_address' => 'Badda Ring Road, Gulshan', 'permanent_address' => 'House # 326, Vill # Kunjpotri, P. O # Chandraproshad - 8300,P. S # Bhola Sadar', 'mail_address' => 'prince@norbangroup.com', 'mobile' => '01755-511880', 'join_date' => '2025-06-25', 'location' => 'NCL'],
            ['employee_code' => '6014', 'name' => 'Nilkanta Sarker', 'department' => 'CAD', 'designation' => 'Executive', 'father_name' => 'Sudhan Sarkar', 'mother_name' => 'Neyoti Rani Sarkar', 'nid_number' => '199 688 189 10', 'present_address' => 'House # M A-88/01, West Merul Badda, Flat # 5 B, Dhaka # 1212', 'permanent_address' => 'Vil # Kushimbi, P. S # Tarash, P. O # Binshara, Sirajganj', 'mail_address' => 'cad@norbangroup.com', 'mobile' => '01755-511890', 'join_date' => '2015-01-05', 'location' => 'NCL'],
            ['employee_code' => '6016', 'name' => 'Al-Amin Sekh', 'department' => 'CAD', 'designation' => 'Executive', 'father_name' => 'Md. Shahidul Islam', 'mother_name' => null, 'nid_number' => '510 256 4498', 'present_address' => 'Waspur, Dhaka', 'permanent_address' => 'Waspur, Dhaka', 'mail_address' => 'cad@norbangroup.com', 'mobile' => '01719-070990', 'join_date' => '2017-11-01', 'location' => 'NCL'],
            ['employee_code' => '1051', 'name' => 'Abul Hossain', 'department' => 'MIS', 'designation' => 'Executive', 'father_name' => 'Md. Mukter Hossain', 'mother_name' => 'Tahmina Begum', 'nid_number' => '914 549 5751', 'present_address' => 'Mamudpur, Bhuigar, Fatullah, Narayanganj, Dhaka', 'permanent_address' => 'Vill # Badarpur, P. O # Kashimpur, P. S # Matlab Dakshin,Chandpur', 'mail_address' => 'abul.hossain@norbangroup.com', 'mobile' => '01709-632653', 'join_date' => '2023-10-01', 'location' => 'NCL'],
            ['employee_code' => '1053', 'name' => 'Shawonoor Rahman', 'department' => 'MIS', 'designation' => 'Data Entry Operator', 'father_name' => 'Md. Shahidur Rahman', 'mother_name' => 'Mst. Shefali Begum', 'nid_number' => '641 250 7987', 'present_address' => 'Asif Villa, Dakkhinkhan, Dhaka', 'permanent_address' => 'Bhuiyan Bari, Gogul Nogo, Char Sindhur, Palash,Narsingdi 1612', 'mail_address' => 'shawon.mis@norbangroup.com', 'mobile' => '01709-632658', 'join_date' => '2024-11-05', 'location' => 'NCL'],
            ['employee_code' => '1054', 'name' => 'Md. Jakir Hossain', 'department' => 'MIS', 'designation' => 'Management Trainee', 'father_name' => 'Md. Jalal Uddin', 'mother_name' => 'Mst. Jahura Begum', 'nid_number' => '598 886 5621', 'present_address' => '1132 / B, Baitul Aman Housing, Adabor, Dhaka # 1207', 'permanent_address' => 'Vill # Uchagram, P. O # Baroipotpl - 2052, P. S # Shorishabari ,Jamalpur', 'mail_address' => null, 'mobile' => '01933-874907', 'join_date' => '2025-12-10', 'location' => 'NCL'],
            ['employee_code' => '5061', 'name' => 'Roshniara Akhter', 'department' => 'Merchandising', 'designation' => 'Executive (Data Entry)', 'father_name' => 'Md. Muhasin Ali', 'mother_name' => 'Most. Raushanara Begum', 'nid_number' => '9429407127333', 'present_address' => 'Badda, Dhaka.', 'permanent_address' => 'Vill # Shantinagar, P. O # Thakurgoan, P. S # Thakurgoan', 'mail_address' => 'roshni@norbangroup.com', 'mobile' => '01724-046219', 'join_date' => '2016-08-18', 'location' => 'NCL'],
            ['employee_code' => '6001', 'name' => 'Shushanta Sarkar', 'department' => 'Production', 'designation' => 'GM (Production and Technical)', 'father_name' => 'Sudhan Sarker', 'mother_name' => 'Neyoti Rani Sarker', 'nid_number' => '08818910014179', 'present_address' => 'House-MA -88/01,West Merul Badda,Fkat-5b,Dhaka-1212', 'permanent_address' => 'Kushimbi,Tarash, Binshara ,Sirajgonj', 'mail_address' => 'sushanta@norbangroup.com', 'mobile' => '01755-511886', 'join_date' => '1996-09-01', 'location' => 'NCL'],
            ['employee_code' => '1518', 'name' => 'Mizanur Rahman', 'department' => 'Admin (Assistant)', 'designation' => 'Executive (Electrical)', 'father_name' => 'Abdul Jallil', 'mother_name' => 'Morzian Begom', 'nid_number' => '825 495 9615', 'present_address' => 'House # 01, Road # 01, Gulshan Avenue, Gulshan # 01,Dhaka', 'permanent_address' => 'Vill # Choto Mohiesmorii, P. O # Forker Hat, P. S # Rajahat,Kurigaram', 'mail_address' => null, 'mobile' => '01709-632699', 'join_date' => '2024-01-01', 'location' => 'NCL'],
            ['employee_code' => '1502', 'name' => 'Nurul Afsar', 'department' => 'Admin (Assistant)', 'designation' => 'Office Assistant', 'father_name' => 'Alom Mia', 'mother_name' => 'Moniza Khatun', 'nid_number' => '751 579 500 93', 'present_address' => 'House # 8 / B, Road # 01, Gulshan-01, Dhaka # 1212', 'permanent_address' => 'House # Aminulla Pilot Bari, Vill # East Rajunagar, P. O # Abdullah Miar Hat - 3807, Kobirhat,Noakhali', 'mail_address' => null, 'mobile' => '01755-511894', 'join_date' => '2005-07-18', 'location' => 'NCL'],
            ['employee_code' => '1503', 'name' => 'Abul Kashem', 'department' => 'Admin (Assistant)', 'designation' => 'Office Assistant', 'father_name' => 'Abdul Kayum', 'mother_name' => 'Anwara Begum', 'nid_number' => '751 479 500 90', 'present_address' => 'T B Gate, Mohakhali, Dhaka', 'permanent_address' => 'Abdul Kayum Cho. Bari, Vill / Road # Chobirpaik, P. O # Abdullah Miar Hat - 3807, Kobirhat,Noakhali', 'mail_address' => null, 'mobile' => '01814-219628', 'join_date' => '2005-12-01', 'location' => 'HAL'],
            ['employee_code' => '10180', 'name' => 'Kajol Mia', 'department' => 'Admin (Assistant)', 'designation' => 'Office Assistant', 'father_name' => 'Mogol Mia', 'mother_name' => 'Saleha Begum', 'nid_number' => '6816447285828', 'present_address' => 'Gulshan # 1, Road # 1, House # 8 / B, Dhaka', 'permanent_address' => 'Vill #  Doulatkandi, P . O # Shapmara Bazar, Thana #  Raipura,Narshindi', 'mail_address' => null, 'mobile' => '01751-240176', 'join_date' => '2009-05-01', 'location' => 'NCL'],
            ['employee_code' => '1507', 'name' => 'Anwar Hossain', 'department' => 'Admin (Assistant)', 'designation' => 'Peon', 'father_name' => 'Alom Mia', 'mother_name' => 'Moniza Khatun', 'nid_number' => '751 479 500 93', 'present_address' => 'Badda, Dhaka', 'permanent_address' => 'House # Aminulla Pilot Bari, Vill # East Rajunagar, P. O # Abdullah Miar Hat - 3807, Kobirhat,Noakhali', 'mail_address' => null, 'mobile' => '01714-574121', 'join_date' => '2010-08-01', 'location' => 'NCL'],
            ['employee_code' => '1513', 'name' => 'Mozammel Hossain', 'department' => 'Admin (Assistant)', 'designation' => 'Peon', 'father_name' => 'Md. Romjan Hossain', 'mother_name' => 'Mrs. Mosarafa Begum', 'nid_number' => '868 842 6199', 'present_address' => 'Badda, Dhaka', 'permanent_address' => 'Vill  # Begumbad (Jaukandi), O. O # Alvir Bazar, P. S # Raipura,Narshindi', 'mail_address' => null, 'mobile' => '01715-677008', 'join_date' => '2017-04-10', 'location' => 'NCL'],
            ['employee_code' => '1521', 'name' => 'Md. Kawsar Miah', 'department' => 'Admin (Assistant)', 'designation' => 'Peon', 'father_name' => 'Md. Ahab Miah', 'mother_name' => 'Hamida Begum', 'nid_number' => '465 473 6190', 'present_address' => 'House # 8 / B, Road # 01, Gulshan # 01', 'permanent_address' => 'Vill # Saherchar, P. O # Saherchar Bazar, P. S # Raipura,Narsingdi', 'mail_address' => null, 'mobile' => '01916-824715', 'join_date' => '2025-10-01', 'location' => 'NCL'],
            ['employee_code' => '1523', 'name' => 'Somon', 'department' => 'Admin (Assistant)', 'designation' => 'Peon', 'father_name' => 'Jaj Miah', 'mother_name' => 'Peara Begum', 'nid_number' => '781 786 2910', 'present_address' => 'Vill # Charni Laxmi, P. O # Charni Laxmi, P. S # Sanmania,Dist # Gazipur', 'permanent_address' => 'Vill # Charni Laxmi, P. O # Charni Laxmi, P. S # Sanmania,Dist # Gazipur', 'mail_address' => null, 'mobile' => '01309-930851', 'join_date' => '2026-01-04', 'location' => 'NCL'],
            ['employee_code' => '1504', 'name' => 'Emdadul Haque', 'department' => 'Admin (Assistant)', 'designation' => 'Caretaker', 'father_name' => 'Lal Mia', 'mother_name' => 'Hasina Begum', 'nid_number' => '7334892689', 'present_address' => 'House # 8 / B, Road # 1, Gulshan # 1,Dhaka', 'permanent_address' => 'Vill # Porulia, P. S # Kalia, P. O # Chachuri Porulia,Narail', 'mail_address' => null, 'mobile' => '01709-632698', 'join_date' => '2007-02-25', 'location' => 'HAL'],
            ['employee_code' => '10182', 'name' => 'Habibullah', 'department' => 'Admin (Assistant)', 'designation' => 'Caretaker', 'father_name' => 'Samsul Islam', 'mother_name' => 'Mrs. Jubeda Khatun', 'nid_number' => '2692619987152', 'present_address' => 'House # 8 / B, Road # 1, Gulshan # 1, Dhaka # 1212', 'permanent_address' => 'Vill # Pachkownia, P. O # Shahagonj, Union # Chintapur, P. S # Gowripur, Mymensingh', 'mail_address' => null, 'mobile' => '01710-927162', 'join_date' => '2017-12-16', 'location' => 'HAL'],
            ['employee_code' => '1501', 'name' => 'Dulal Hossain', 'department' => 'Admin (Assistant)', 'designation' => 'Cook', 'father_name' => 'Afsar Mia', 'mother_name' => 'Rosara Begum', 'nid_number' => '2691648052338', 'present_address' => 'Zigatola, Dhanmondi, Dhaka', 'permanent_address' => 'Vill # Chorkoja, P. O # Chorkoja, P. S # Nolehiti,Barisal', 'mail_address' => null, 'mobile' => '01731-403097', 'join_date' => '1992-01-01', 'location' => 'NCL'],
            ['employee_code' => '1517', 'name' => 'Abbas Talukder', 'department' => 'Admin (Assistant)', 'designation' => 'Cook', 'father_name' => 'Md. Abdul Khalek Talukder', 'mother_name' => 'Mst. Rizia Begum', 'nid_number' => '373 233 0109', 'present_address' => 'Holding # 71, Hosue # Aich Para, Shaj Uddin Sarker Road, Tongi, Gazipur,Dhaka', 'permanent_address' => 'Vill / Road # Jirail, P. O # Jirail, P. S # Bakergonj,Barisal', 'mail_address' => null, 'mobile' => '01985-849763', 'join_date' => '2023-06-08', 'location' => 'NCL'],
            ['employee_code' => '1522', 'name' => 'Md. Liton Hossain', 'department' => 'Admin (Assistant)', 'designation' => 'Cook', 'father_name' => 'Md. Nazrul Islam', 'mother_name' => 'Nilu Begum', 'nid_number' => '506 889 9359', 'present_address' => 'House # 53, Road # 12, Uttara, Turag,Dhaka # 1230', 'permanent_address' => 'House # 53, Road # 12, Uttara, Turag,Dhaka # 1230', 'mail_address' => null, 'mobile' => '01741-083692', 'join_date' => '2026-01-04', 'location' => 'NCL'],
            ['employee_code' => '1520', 'name' => 'Kajal Miah', 'department' => 'Admin (Assistant)', 'designation' => 'Cook', 'father_name' => 'Kayaum Miah', 'mother_name' => 'Rehana Begum', 'nid_number' => '280 425 8818', 'present_address' => 'House # 8 / B, Road # 01, Gulshan # 01,Dhaka # 1212', 'permanent_address' => 'Vill # Kadura, P. O # Sams Village, P. S # Nabinagara,Brahman Baria', 'mail_address' => null, 'mobile' => '01731-240517', 'join_date' => '2025-01-20', 'location' => 'HAL'],
            ['employee_code' => '1514', 'name' => 'Nurul Islam', 'department' => 'Admin (Assistant)', 'designation' => 'Cleaner', 'father_name' => 'Md. Nuruzzaman', 'mother_name' => 'Rizia Khatun', 'nid_number' => '4201049147', 'present_address' => 'Middle Badda, Adarsho Nagar, P. O # Gulshan,Dhaka # 1212', 'permanent_address' => 'Dewan Bari, Vill # Ludua, P. O # Voia Bari, P. S # Raipur,Dis # Lakshmipur', 'mail_address' => null, 'mobile' => '01927-265107', 'join_date' => '2022-09-03', 'location' => 'NCL'],
            ['employee_code' => '1511', 'name' => 'Md. Mahbub Alam', 'department' => 'Admin (Assistant)', 'designation' => 'Cleaner', 'father_name' => 'Md. Mufazzol Hosen', 'mother_name' => 'Mst. Champa Khatun', 'nid_number' => '151 875 6315', 'present_address' => 'T & T Colony, Banani, Dhaka # 1213', 'permanent_address' => 'Vill # Shalchura, P. O # Gazirkhamar, P. S # Sherpur,Sherpur', 'mail_address' => null, 'mobile' => '01406-301398', 'join_date' => '2025-09-01', 'location' => 'HAL'],
            ['employee_code' => '1706', 'name' => 'Kuddus Madbor', 'department' => 'Admin (Driver)', 'designation' => 'Driver', 'father_name' => 'Yasin Matbor', 'mother_name' => 'Mst. Jobeda Begum', 'nid_number' => '9563115717', 'present_address' => 'Badda, Gulshan, Dhaka', 'permanent_address' => 'Vil # Chargajipur, P. O # Joynagar, P. S # Palong,Shariatpur', 'mail_address' => null, 'mobile' => '01759-724537', 'join_date' => '2009-12-01', 'location' => 'NCL'],
            ['employee_code' => '1707', 'name' => 'Motaleb Hossain', 'department' => 'Admin (Driver)', 'designation' => 'Driver', 'father_name' => 'Arman Mondol', 'mother_name' => 'Mrs. Boro Bibi', 'nid_number' => '269 042 137 68', 'present_address' => 'Badda', 'permanent_address' => 'Vill # West Harua, P. O # Roton Dia, P. S # Pangsha,Faridpur', 'mail_address' => null, 'mobile' => '01755-511892', 'join_date' => '2010-05-10', 'location' => 'NCL'],
            ['employee_code' => '1708', 'name' => 'Ismail Sarkar', 'department' => 'Admin (Driver)', 'designation' => 'Driver', 'father_name' => 'Sherajul Islam Sarkar', 'mother_name' => 'Rabeya Khatun', 'nid_number' => '461 985 4831', 'present_address' => '40 South Kamalapur, Motijheel,Dhaka', 'permanent_address' => 'Vill # Mokposskone, P. O # Mohammadpur Bazar, P. S # Debidwar,Comilla', 'mail_address' => null, 'mobile' => '01755-511898', 'join_date' => '2023-07-08', 'location' => 'NCL'],
            ['employee_code' => '1710', 'name' => 'Md. Abdus Sattar Khan', 'department' => 'Admin (Driver)', 'designation' => 'Driver', 'father_name' => 'Md. Sinto Khan', 'mother_name' => 'Mst. Halima Begum', 'nid_number' => '331 303 181 0414', 'present_address' => 'House # 118, Chandura, P. O # Gasa - 1704, P. S # Gazipur,Dhaka', 'permanent_address' => 'Vill # Adashan, P. O # Moderhat, P. S # Damudda,Shariotpur', 'mail_address' => null, 'mobile' => '01721-866785', 'join_date' => '2025-11-01', 'location' => 'NCL'],
            ['employee_code' => '1801', 'name' => 'Ruhul', 'department' => 'Admin (Driver)', 'designation' => 'Driver', 'father_name' => 'Md. Tara Mia', 'mother_name' => 'Mrs. Nurjahan', 'nid_number' => '269 261 966 08', 'present_address' => 'House # Kollan 559, Korail Bosti, P. O # Banani # 1213', 'permanent_address' => 'Pat Pasha, Cunjonogor,Faridpur', 'mail_address' => null, 'mobile' => null, 'join_date' => '2014-10-01', 'location' => 'NCL'],
            ['employee_code' => '1841', 'name' => 'Ripon Hossain', 'department' => 'Admin (Driver)', 'designation' => 'Driver', 'father_name' => 'Md. Atuar Rahman', 'mother_name' => 'Rokeya Begum', 'nid_number' => null, 'present_address' => 'House # 773, Block # G, Bashundhara, Dhaka', 'permanent_address' => '54/4, Kalachadpur, Kirtipur, Naogan', 'mail_address' => null, 'mobile' => '01733-663447', 'join_date' => '2018-07-01', 'location' => 'HAL'],
            ['employee_code' => '1839', 'name' => 'Sayed Baktiar Rahman', 'department' => 'Admin (Driver)', 'designation' => 'Driver', 'father_name' => 'Sayed Jinnatul Rahman', 'mother_name' => 'Mst. Khaleda Ferdousi', 'nid_number' => '1990 611 2315', 'present_address' => 'House # 8, Road # 10, Gudara Ghat, Badda,Dhaka', 'permanent_address' => 'Vill # Fulbaria, P. O # Shahgonj, P. S # Gouripur,Mymansingh', 'mail_address' => null, 'mobile' => '01757-803234', 'join_date' => '2018-05-03', 'location' => 'NCL'],
            ['employee_code' => '1859', 'name' => 'Samiul Islam', 'department' => 'Admin (Driver)', 'designation' => 'Driver', 'father_name' => 'Md. Tofig Uddin', 'mother_name' => 'Mrs. Sofura Begum', 'nid_number' => '19902716063000', 'present_address' => 'House # 8 / B, Road # 01, Gulshan # 01,Dhaka # 1212', 'permanent_address' => 'Vill # Ververy, Post # Banglabazar, P. S # Khanshama,Dinajpur', 'mail_address' => null, 'mobile' => '01748-607456', 'join_date' => '2021-06-14', 'location' => 'NCL'],
            ['employee_code' => '1860', 'name' => 'Kalo Akond Kabir', 'department' => 'Admin (Driver)', 'designation' => 'Driver', 'father_name' => 'Md. Ahmed Ali Akond', 'mother_name' => 'Ayna Bibi', 'nid_number' => '4626468518', 'present_address' => '428, Faedabad, Beribad Road, P. O # Faedabad, Uttora, Dhaka', 'permanent_address' => '428, Faedabad, Beribad Road, P. O # Faedabad, Uttora, Dhaka', 'mail_address' => null, 'mobile' => '01916-386669', 'join_date' => '2021-10-02', 'location' => 'NCL'],
            ['employee_code' => '1872', 'name' => 'Enamul', 'department' => 'Admin (Driver)', 'designation' => 'Driver', 'father_name' => 'Md. Ali Hossain', 'mother_name' => 'Monowara', 'nid_number' => '1468274251', 'present_address' => 'Section # 11, Block # C, Baunuabandh, Road # 01, House # 01,Pallabi, Mirpur, Dhaka # 1216', 'permanent_address' => 'Vill # Haragas, P. O # Kaunia, P. S # Kaunia,Rangpur', 'mail_address' => null, 'mobile' => '01790-723688', 'join_date' => '2023-03-11', 'location' => 'NCL'],
            ['employee_code' => '1882', 'name' => 'Abul', 'department' => 'Admin (Driver)', 'designation' => 'Driver', 'father_name' => 'Md. Shamjed Ali', 'mother_name' => 'Mahmuda Begum', 'nid_number' => '956 940 8728', 'present_address' => 'Sukrabad Dhanmondi 32 Dhaka', 'permanent_address' => 'Dakhin Koikhali, Binapani, Khathalia, Jhalokati', 'mail_address' => null, 'mobile' => '01955-375149', 'join_date' => '2024-07-13', 'location' => 'NCL'],
            ['employee_code' => '1842', 'name' => 'Md. Nur Naby Miah', 'department' => 'Admin (Driver)', 'designation' => 'Driver', 'father_name' => 'Md. Nur Islam', 'mother_name' => 'Mst. Jahanara Begum', 'nid_number' => '460 621 6739', 'present_address' => '94, Civil Motaleb Villa, Bashabo,Dhaka # 1214', 'permanent_address' => 'Vill # Prannath Pur, P. O # Venda Bari, P. S # Pirgaj,Rangpur', 'mail_address' => null, 'mobile' => '01745-682316', 'join_date' => '2055-10-21', 'location' => 'NCL'],
            ['employee_code' => '1887', 'name' => 'Ashraful Sardar', 'department' => 'Admin (Driver)', 'designation' => 'Driver', 'father_name' => 'Siddik Sardar', 'mother_name' => 'Jahanara Begum', 'nid_number' => '734 806 1412', 'present_address' => '5/1, Lalasharai, Dhamalkot, P. O # Dhaka Cantonment, P. S # Vashantek,Dhaka # 1206', 'permanent_address' => 'Vill # Dhigholia, P. O # Kola Dhogholia - 7510, P. S # Lohagara,Narail', 'mail_address' => null, 'mobile' => '01911-956855', 'join_date' => '2025-04-26', 'location' => 'NCL'],
        ];

        foreach ($employees as $row) {
            $department = Department::firstOrCreate(['name' => $row['department']]);
            $position   = Position::firstOrCreate(['name' => $row['designation']]);

            // AssetLocation keys off location_name, and a few rows have no site yet
            $location = $row['location']
                ? AssetLocation::firstOrCreate(['location_name' => $row['location']])
                : null;

            Employee::updateOrCreate(
                ['employee_code' => $row['employee_code']],
                [
                    'name'              => $row['name'],
                    'department_id'     => $department->id,
                    'position_id'       => $position->id,
                    'location_id'       => $location?->id,
                    'father_name'       => $row['father_name'],
                    'mother_name'       => $row['mother_name'],
                    'nid_number'        => $row['nid_number'],
                    'present_address'   => $row['present_address'],
                    'permanent_address' => $row['permanent_address'],
                    'mail_address'      => $row['mail_address'],
                    'mobile'            => $row['mobile'],
                    'join_date'         => $row['join_date'],
                ]
            );
        }
    }
}
