import { Link } from '@inertiajs/react';
import { ArrowLeft, Mail, Pencil, Phone, UserRound } from 'lucide-react';

import AppLayout from '@/layouts/app-layout';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';

interface AssetRow { id: number; asset_code: string; asset_name: string; category: string | null; location: string | null; status: string; }
interface Assignment { id: number; asset_id: number; asset_code: string | null; asset_name: string | null; assigned_at: string | null; returned_at: string | null; condition: string | null; return_condition: string | null; handler: string | null; }
interface Employee { id: number; employee_code: string; name: string; image_url: string | null; department: string | null; position: string | null; location: string | null; mobile: string | null; mail_address: string | null; join_date: string | null; father_name: string | null; mother_name: string | null; nid_number: string | null; present_address: string | null; permanent_address: string | null; assets: AssetRow[]; assignments: Assignment[]; }
interface Props { employee: Employee; canManage: boolean; }
const text = (value: string | null) => value || '-';
const humanise = (value: string | null) => value ? value.replace(/_/g, ' ').toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase()) : '-';

export default function EmployeeShow({ employee, canManage }: Props) {
    return <AppLayout title={employee.name} description={`${employee.employee_code} · ${text(employee.position)}`} actions={<><Button variant="outline" asChild><Link href="/employees"><ArrowLeft /> Back</Link></Button>{canManage && <Button asChild><Link href={`/employees/${employee.id}/edit`}><Pencil /> Edit</Link></Button>}</>}>
        <div className="grid gap-6 lg:grid-cols-[320px_1fr]">
            <div className="space-y-6"><Card><CardContent className="flex flex-col items-center p-6 text-center">{employee.image_url ? <img src={employee.image_url} alt={employee.name} className="mb-4 size-40 rounded-full object-cover" /> : <div className="mb-4 flex size-40 items-center justify-center rounded-full bg-muted text-muted-foreground"><UserRound className="size-16" /></div>}<h2 className="text-xl font-semibold">{employee.name}</h2><p className="text-muted-foreground">{text(employee.position)}</p><p className="text-sm text-muted-foreground">{text(employee.department)}</p><Badge className="mt-3">{employee.employee_code}</Badge></CardContent></Card><Card><CardHeader><CardTitle>Contact</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p className="flex gap-2"><Phone className="size-4 text-muted-foreground" />{text(employee.mobile)}</p><p className="flex gap-2"><Mail className="size-4 text-muted-foreground" />{text(employee.mail_address)}</p><p><b>Location:</b> {text(employee.location)}</p><p><b>Join date:</b> {text(employee.join_date)}</p></CardContent></Card></div>
            <div className="space-y-6"><Card><CardHeader><CardTitle>Personal Information</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 text-sm"><p><b>Father's name:</b><br />{text(employee.father_name)}</p><p><b>Mother's name:</b><br />{text(employee.mother_name)}</p><p><b>NID number:</b><br />{text(employee.nid_number)}</p><p><b>Present address:</b><br />{text(employee.present_address)}</p><p><b>Permanent address:</b><br />{text(employee.permanent_address)}</p></CardContent></Card><Card><CardHeader><CardTitle>Assets Currently Held <Badge variant="secondary">{employee.assets.length}</Badge></CardTitle></CardHeader><CardContent><div className="overflow-x-auto rounded-md border"><Table><TableHeader><TableRow><TableHead>Code</TableHead><TableHead>Name</TableHead><TableHead>Category</TableHead><TableHead>Location</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{employee.assets.length === 0 ? <TableRow><TableCell colSpan={5} className="h-20 text-center text-muted-foreground">No asset is assigned to this employee.</TableCell></TableRow> : employee.assets.map((asset) => <TableRow key={asset.id}><TableCell><Link className="font-medium hover:underline" href={`/inventory/${asset.id}`}>{asset.asset_code}</Link></TableCell><TableCell>{asset.asset_name}</TableCell><TableCell>{text(asset.category)}</TableCell><TableCell>{text(asset.location)}</TableCell><TableCell><Badge variant="outline">{humanise(asset.status)}</Badge></TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card><Card><CardHeader><CardTitle>Handover History</CardTitle></CardHeader><CardContent><div className="overflow-x-auto rounded-md border"><Table><TableHeader><TableRow><TableHead>Asset</TableHead><TableHead>Assigned</TableHead><TableHead>Returned</TableHead><TableHead>Condition</TableHead><TableHead>Handler</TableHead></TableRow></TableHeader><TableBody>{employee.assignments.length === 0 ? <TableRow><TableCell colSpan={5} className="h-20 text-center text-muted-foreground">No handover recorded yet.</TableCell></TableRow> : employee.assignments.map((row) => <TableRow key={row.id}><TableCell><Link className="font-medium hover:underline" href={`/inventory/${row.asset_id}`}>{row.asset_code || '-'}</Link><br /><span className="text-xs text-muted-foreground">{row.asset_name}</span></TableCell><TableCell>{text(row.assigned_at)}</TableCell><TableCell>{row.returned_at || <Badge>Current</Badge>}</TableCell><TableCell>{humanise(row.condition)}{row.return_condition && ` → ${humanise(row.return_condition)}`}</TableCell><TableCell>{text(row.handler)}</TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card></div>
        </div>
    </AppLayout>;
}
